# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.5.4-hotfix.2-stable.tar.xz -o flutter.tar.xz
    tar xf ./flutter.tar.xz
  displayName: 'Install Flutter'

- script: |
    ./flutter/bin/flutter test
  displayName: 'Run Test'
